-- =====================================================================
-- V18__kidloop_test_activities_calm_pool.sql (yuklenen dosya V10 adliydi; V10/V17 dolu oldugu icin V18)
-- 34 test etkinligi (id 129-162): dusuk duyusal yuk, anne yaninda katilim
-- Amac: korunmaci duyusal tip ve yuksek ayrilik kaygisi olan cocuklarda
--       plan kurulamama sorununu kapatmak
-- Uretim: 15 Agustos 2026
-- =====================================================================
-- ONKOSUL: target_domain CHECK 7 degerli, difficulty CHECK 1-4 olmali.
-- Idempotent: ON CONFLICT (id) DO UPDATE.
-- =====================================================================

BEGIN;

INSERT INTO activities (
    id, scope, workshop_id, title, description,
    min_age_months, max_age_months, status,
    target_intelligence, secondary_intelligence, target_domain,
    difficulty, duration_minutes, involvement_type,
    noise_load, visual_load, physical_intensity, is_scaffolded
) VALUES
    (129, 'HOME', NULL, 'Kucakta yavaş yan dönüş', 'Bebeği kucağınızda ya da minderde çok yavaş bir tempoyla yan yatırıp sırtüstü döndürerek gövde kaslarını uyandıran sessiz bir hareket oyunu.',
     0, 10, 'PUBLISHED',
     'BODILY_KINAESTHETIC', 'INTRAPERSONAL', 'GROSS_MOTOR',
     1, 5, 'BIRLIKTE',
     1, 1, 2, TRUE),
    (130, 'HOME', NULL, 'Uzanıp alma oyunu sessiz', 'Bebeğin görüş alanında duran yumuşak bir nesneye doğru uzanmasını, sonra nesneyi biraz yana alarak gövdesini çevirmesini sağlayan iki adımlı sakin oyun.',
     3, 12, 'PUBLISHED',
     'BODILY_KINAESTHETIC', 'VISUAL_SPATIAL', 'GROSS_MOTOR',
     2, 5, 'BIRLIKTE',
     1, 2, 2, TRUE),
    (131, 'HOME', NULL, 'Fısıltıyla isim oyunu', 'Bebeğin kulağına çok alçak sesle adını ve gün içindeki nesnelerin adını söyleyerek dil girdisini gürültüsüz veren bir tanışma oyunu.',
     0, 12, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'INTRAPERSONAL', 'LANGUAGE',
     1, 5, 'BIRLIKTE',
     1, 1, 1, TRUE),
    (132, 'HOME', NULL, 'Tek nesne izleme loş ışıkta', 'Loş bir odada tek bir sade nesnenin yavaşça hareket ettirilmesiyle görsel takibi çalıştıran, hiç ses içermeyen bir izleme oyunu.',
     2, 12, 'PUBLISHED',
     'VISUAL_SPATIAL', 'NATURALISTIC', 'SENSORY',
     1, 5, 'GOZETIMLI',
     1, 2, 1, TRUE),
    (133, 'HOME', NULL, 'Kalp sesi dinleme', 'Bebeği göğsünüze yatırıp kalp atışınızı dinlemesine izin veren, sakinleşme ritüeline dönüşebilen sessiz bir bağ oyunu.',
     0, 12, 'PUBLISHED',
     'INTRAPERSONAL', 'MUSICAL', 'SOCIAL_EMOTIONAL',
     1, 5, 'BIRLIKTE',
     1, 1, 1, TRUE),
    (134, 'HOME', NULL, 'Örtü altında kaybolan nesne', 'Bebeğin gözü önünde ince bir örtünün altına konan nesnenin hâlâ orada olduğunu keşfetmesini sağlayan sessiz bir nesne sürekliliği oyunu.',
     6, 14, 'PUBLISHED',
     'LOGICAL_MATHEMATICAL', 'VISUAL_SPATIAL', 'COGNITIVE',
     2, 5, 'BIRLIKTE',
     1, 2, 1, TRUE),
    (135, 'HOME', NULL, 'Yastıktan yastığa sessiz geçiş', 'Yere dizilen iki üç yastığın üstünden elinizden tutarak geçme oyunu; denge çalışır ama ne ses ne kalabalık görüntü vardır.',
     12, 24, 'PUBLISHED',
     'BODILY_KINAESTHETIC', 'VISUAL_SPATIAL', 'GROSS_MOTOR',
     2, 10, 'BIRLIKTE',
     1, 2, 2, TRUE),
    (136, 'HOME', NULL, 'Yavaş tempoda birlikte esneme', 'Anne ve çocuğun karşılıklı oturup kollarını yukarı kaldırma, öne uzanma gibi üç dört sade hareketi çok yavaş yapması.',
     12, 20, 'PUBLISHED',
     'BODILY_KINAESTHETIC', 'INTRAPERSONAL', 'GROSS_MOTOR',
     1, 5, 'BIRLIKTE',
     1, 1, 2, TRUE),
    (137, 'HOME', NULL, 'Sessiz resimli kitap turu', 'Resimli bir kitabın sayfalarını çevirip her sayfada tek bir nesneyi alçak sesle adlandırma; sayfa başına bir kelime, hiç hikâye anlatmadan.',
     14, 26, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'INTERPERSONAL', 'LANGUAGE',
     2, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (138, 'HOME', NULL, 'Karşılıklı yumuşak top yuvarlama', 'Yerde karşılıklı oturup yumuşak bir topu birbirine yuvarlama; sıra almanın en sade hali.',
     12, 24, 'PUBLISHED',
     'INTERPERSONAL', 'BODILY_KINAESTHETIC', 'SOCIAL_EMOTIONAL',
     2, 5, 'BIRLIKTE',
     1, 2, 2, TRUE),
    (139, 'HOME', NULL, 'Kaba içine koyma çıkarma', 'Birkaç yumuşak nesneyi bir kutuya koyup çıkarma; sıralı adım ve içinde-dışında kavramını sessizce çalıştıran bağımsızlığa yakın ama gözetimli bir oyun.',
     15, 26, 'PUBLISHED',
     'LOGICAL_MATHEMATICAL', 'VISUAL_SPATIAL', 'COGNITIVE',
     2, 10, 'GOZETIMLI',
     1, 2, 1, TRUE),
    (140, 'HOME', NULL, 'Pencereden sessiz gökyüzü izleme', 'Pencere kenarına oturup bulutları, ağaç yapraklarını ya da yağmuru sessizce izlemek; hiçbir yönerge yok, yalnız birlikte bakmak.',
     12, 24, 'PUBLISHED',
     'NATURALISTIC', 'VISUAL_SPATIAL', 'SENSORY',
     1, 5, 'BIRLIKTE',
     1, 2, 1, TRUE),
    (141, 'HOME', NULL, 'Fısıltı kuklası sohbeti', 'Elinize taktığınız yumuşak kuklanın çok alçak sesle selam verip iki soru sorduğu, çocuğun cevapladığı sakin bir sohbet oyunu.',
     24, 36, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'INTERPERSONAL', 'LANGUAGE',
     2, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (142, 'HOME', NULL, 'Bu ne oyunu sade kartlarla', 'Tek nesne resmi olan üç dört kartı sırayla gösterip adını söyletme; en sade adlandırma çalışması.',
     24, 36, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'VISUAL_SPATIAL', 'LANGUAGE',
     1, 5, 'BIRLIKTE',
     1, 2, 1, TRUE),
    (143, 'HOME', NULL, 'Yavaş nefes balonu sessiz', 'Elleri karnın üstünde, birlikte üç kez yavaş nefes alıp verme; balonu şişirip söndürme benzetmesiyle anlatılan sakinleşme çalışması.',
     24, 40, 'PUBLISHED',
     'INTRAPERSONAL', 'VERBAL_LINGUISTIC', 'SELF_REGULATION',
     2, 5, 'BIRLIKTE',
     1, 1, 1, TRUE),
    (144, 'HOME', NULL, 'İkişer eşleştirme sessiz', 'Aynı olan iki nesneyi (çorap, kaşık, blok) bulup yan yana koyma; sade, gürültüsüz bir eşleştirme çalışması.',
     24, 38, 'PUBLISHED',
     'LOGICAL_MATHEMATICAL', 'VISUAL_SPATIAL', 'COGNITIVE',
     2, 10, 'GOZETIMLI',
     1, 2, 1, TRUE),
    (145, 'HOME', NULL, 'Duygu yüzleri aynada', 'Aynanın karşısına geçip mutlu, üzgün, şaşkın yüzleri birlikte yapma ve adlandırma; sessiz bir duygu tanıma oyunu.',
     26, 40, 'PUBLISHED',
     'INTERPERSONAL', 'INTRAPERSONAL', 'SOCIAL_EMOTIONAL',
     2, 10, 'BIRLIKTE',
     1, 2, 1, TRUE),
    (146, 'HOME', NULL, 'Sessiz ritim: parmak ucuyla vuruş', 'Masaya ya da dize parmak ucuyla çok hafif ritim tutma ve çocuğun tekrar etmesi; ses neredeyse yok, ritim var.',
     24, 36, 'PUBLISHED',
     'MUSICAL', 'BODILY_KINAESTHETIC', 'SENSORY',
     2, 5, 'BIRLIKTE',
     2, 1, 2, TRUE),
    (147, 'HOME', NULL, 'Günümü anlatıyorum üç cümle', 'Çocuğun gün içinde yaptığı üç şeyi sırayla anlatması; anne yalnız soru sorup bekler, sessiz ve baskısız bir anlatı çalışması.',
     36, 48, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'INTRAPERSONAL', 'LANGUAGE',
     2, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (148, 'HOME', NULL, 'Ne olurdu oyunu sessiz', 'Basit varsayım soruları sorup cevap bekleme: "Yağmur yağarsa ne yaparız?"; kuralı akılda tutup cevap üretmeyi çalıştırır.',
     38, 50, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'LOGICAL_MATHEMATICAL', 'LANGUAGE',
     3, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (149, 'HOME', NULL, 'Sakinlik köşesi kurma', 'Evin bir köşesine yastık ve battaniyeyle çocuğun kendi sakinleşme alanını birlikte kurmak; kurma işi de etkinliğin parçası.',
     36, 50, 'PUBLISHED',
     'INTRAPERSONAL', 'VISUAL_SPATIAL', 'SELF_REGULATION',
     2, 10, 'BIRLIKTE',
     1, 2, 1, TRUE),
    (150, 'HOME', NULL, 'Sıralama: küçükten büyüğe sessiz', 'Üç dört nesneyi boyutuna göre sıraya dizme; kuralı akılda tutup uygulamayı gerektiren sade bir çalışma.',
     38, 52, 'PUBLISHED',
     'LOGICAL_MATHEMATICAL', 'VISUAL_SPATIAL', 'COGNITIVE',
     3, 10, 'GOZETIMLI',
     1, 2, 1, TRUE),
    (151, 'HOME', NULL, 'Sıra bizde: sessiz sıra oyunu', 'Basit bir işi (blok dizme, kart çevirme) sırayla yapma; her turda kimin sırası olduğunu söyleyerek sabrı çalıştırma.',
     36, 48, 'PUBLISHED',
     'INTERPERSONAL', 'VERBAL_LINGUISTIC', 'SOCIAL_EMOTIONAL',
     2, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (152, 'HOME', NULL, 'Sessiz doğa masası', 'Dışarıdan toplanan üç dört doğal nesneyi (taş, yaprak, kozalak) masaya dizip dokunarak inceleme; hiç konuşmadan, çocuğun kendi temposunda.',
     36, 50, 'PUBLISHED',
     'NATURALISTIC', 'INTRAPERSONAL', 'SENSORY',
     2, 10, 'GOZETIMLI',
     1, 2, 1, TRUE),
    (153, 'HOME', NULL, 'Duygu kartları sessiz eşleştirme', 'Duygu yüzü çizili kartları çekip o duyguyu ne zaman hissettiğini anlatma; sakin, karşılıklı bir duygu sohbeti.',
     48, 60, 'PUBLISHED',
     'INTERPERSONAL', 'VERBAL_LINGUISTIC', 'SOCIAL_EMOTIONAL',
     2, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (154, 'HOME', NULL, 'Teşekkür turu', 'Gün içinde teşekkür ettiğiniz üç şeyi sırayla söyleme; iki dakikalık, malzemesiz, çok sakin bir kapanış ritüeli.',
     48, 62, 'PUBLISHED',
     'INTERPERSONAL', 'INTRAPERSONAL', 'SOCIAL_EMOTIONAL',
     2, 5, 'BIRLIKTE',
     1, 1, 1, TRUE),
    (155, 'HOME', NULL, 'Hikâyeyi birlikte tamamlama', 'Anne bir cümleyle hikâye başlatır, çocuk devam eder, sırayla ilerler; sessiz, yaratıcı bir dil oyunu.',
     48, 62, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'INTERPERSONAL', 'LANGUAGE',
     3, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (156, 'HOME', NULL, 'Bugünkü havam çizimi', 'Çocuğun o anki duygusunu bir hava durumu simgesiyle (güneş, bulut, yağmur) çizmesi; konuşmaya gerek bırakmayan sessiz bir duygu ifadesi.',
     48, 62, 'PUBLISHED',
     'INTRAPERSONAL', 'VISUAL_SPATIAL', 'SELF_REGULATION',
     2, 10, 'BIRLIKTE',
     1, 2, 1, TRUE),
    (157, 'HOME', NULL, 'Sessiz tahmin kutusu', 'Kapalı bir kutunun içindeki nesneyi yalnız dokunarak tahmin etme; ipucu toplayıp sonuç çıkarmayı çalıştırır.',
     48, 62, 'PUBLISHED',
     'LOGICAL_MATHEMATICAL', 'VERBAL_LINGUISTIC', 'COGNITIVE',
     3, 10, 'GOZETIMLI',
     1, 2, 1, TRUE),
    (158, 'HOME', NULL, 'Sen olsaydın ne yapardın', 'Basit sosyal durumlar anlatıp çocuğun ne yapacağını sorma; başkasının yerine geçme becerisini sessizce çalıştırır.',
     60, 72, 'PUBLISHED',
     'INTERPERSONAL', 'INTRAPERSONAL', 'SOCIAL_EMOTIONAL',
     3, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (159, 'HOME', NULL, 'Sessiz plan toplantısı', 'Yarın yapılacak iki üç işi birlikte konuşup sıraya koyma; çocuğun kendi gününü planlamaya katılması.',
     60, 72, 'PUBLISHED',
     'INTERPERSONAL', 'VERBAL_LINGUISTIC', 'SOCIAL_EMOTIONAL',
     2, 10, 'BIRLIKTE',
     2, 2, 1, TRUE),
    (160, 'HOME', NULL, 'Sabır sayacı sessiz', 'Bir dakika boyunca hiç konuşmadan oturup sonra ne duyduğunu anlatma; bekleme ve dikkat toplama çalışması.',
     60, 72, 'PUBLISHED',
     'INTRAPERSONAL', 'LOGICAL_MATHEMATICAL', 'SELF_REGULATION',
     3, 10, 'BIRLIKTE',
     1, 2, 1, TRUE),
    (161, 'HOME', NULL, 'Kendi kitabımı yapıyorum', 'Üç sayfalık minik bir kitap katlayıp her sayfaya bir olay çizmesi; hikâye kurgusunu tek başına üretmesi.',
     60, 72, 'PUBLISHED',
     'VERBAL_LINGUISTIC', 'INTRAPERSONAL', 'LANGUAGE',
     3, 10, 'GOZETIMLI',
     1, 2, 1, TRUE),
    (162, 'HOME', NULL, 'Sessiz labirent çizimi', 'Kâğıda basit bir labirent çizip çözmesi, sonra kendi labirentini çizmesi; planlama ve uzamsal düşünme çalışması.',
     60, 72, 'PUBLISHED',
     'VISUAL_SPATIAL', 'LOGICAL_MATHEMATICAL', 'COGNITIVE',
     3, 10, 'GOZETIMLI',
     1, 2, 1, TRUE)
ON CONFLICT (id) DO UPDATE SET
    scope = EXCLUDED.scope,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    min_age_months = EXCLUDED.min_age_months,
    max_age_months = EXCLUDED.max_age_months,
    status = EXCLUDED.status,
    target_intelligence = EXCLUDED.target_intelligence,
    secondary_intelligence = EXCLUDED.secondary_intelligence,
    target_domain = EXCLUDED.target_domain,
    difficulty = EXCLUDED.difficulty,
    duration_minutes = EXCLUDED.duration_minutes,
    involvement_type = EXCLUDED.involvement_type,
    noise_load = EXCLUDED.noise_load,
    visual_load = EXCLUDED.visual_load,
    physical_intensity = EXCLUDED.physical_intensity,
    is_scaffolded = EXCLUDED.is_scaffolded;

INSERT INTO activity_instructions (
    activity_id, intro, purpose, why_it_matters,
    easier_variation, harder_variation, observation_tip, safety_notes
) VALUES
    (129, 'Işıkları kısın, odada tek ses sizin sesiniz olsun. Bebeği sırtüstü yatırın.', 'Gövde ve boyun kaslarını, bebeği hiç irkiltmeden çalıştırmak.',
     'Dönme hareketi emeklemenin ilk provasıdır; sakin tempoda yapıldığında bebek hareketi kendi bedeninden öğrenir, korkmadan tekrar eder.',
     'Yalnız başını yana çevirmesine eşlik edin, gövdeyi hiç döndürmeyin.',
     'Dönüşün sonunda birkaç saniye yan yatışta bekletip kendi kendine geri dönmesini bekleyin.',
     'Dönerken ellerini kullanıp kullanmadığına bakın; bir eliyle kendini itmeye başladıysa bir sonraki basamağa yaklaşıyor demektir.',
     'Yumuşak ve düz bir zeminde yapın. Bebek huzursuzlanırsa hemen bırakın.'),
    (130, 'Bebeği karnüstü ya da sırtüstü yatırın, sevdiği yumuşak bir nesneyi bir kol boyu uzağa koyun.', 'Uzanma ve gövdeyi çevirme hareketini birbirine bağlamak.',
     'Bir hedefe uzanmak, bebeğin ilk amaçlı hareketidir; nesne yana alındığında hareket iki adıma çıkar ve bebek gövdesini kullanmayı öğrenir.',
     'Nesneyi elinin hemen yanına koyun, yalnız uzanması yeterli olsun.',
     'Nesneyi aldıktan sonra diğer tarafa koyup ikinci kez çevirmesini isteyin.',
     'Uzanırken vücudunun hangi tarafını kullanmayı tercih ettiğine bakın.',
     'Nesne ağzına gidebileceği için küçük parçalı olmasın.'),
    (131, 'Sessiz bir odada bebeği kucağınıza alın, yüzünüz onun yüzüne yakın olsun.', 'Dil girdisini duyusal yük eklemeden vermek.',
     'Bebek dili sesin tonundan öğrenir; fısıltı hem net hem de sinir sistemini yormayan bir girdi biçimidir.',
     'Yalnız adını söyleyin, nesne adlandırmaya geçmeyin.',
     'Kısa iki kelimelik cümleler kurun: "Anne burada", "El sıcak".',
     'Fısıltıya döndüğünüzde sesin geldiği yöne bakıp bakmadığına dikkat edin.',
     'Kulağına çok yakın konuşmayın, yarım karış mesafe yeterli.'),
    (132, 'Perdeleri yarı kapatın, odada tek bir sade nesne bulunsun.', 'Görsel takibi minimum uyaranla çalıştırmak.',
     'Aşırı uyarandan kaçınan bebekte görsel gelişim, tek nesne ve sade arka planla desteklenir; kalabalık görüntü bebeği kapanmaya iter.',
     'Nesneyi hiç hareket ettirmeden yalnız gösterin.',
     'Nesneyi yavaşça yukarı aşağı da hareket ettirin.',
     'Gözüyle nesneyi kaç saniye takip edebildiğini sayın.',
     'Parlak ışık ve yanıp sönen oyuncak kullanmayın.'),
    (133, 'Sessiz bir odada oturun, bebeği göğsünüze yatırın.', 'Bebeğin sinir sistemini annenin ritmiyle düzenlemek.',
     'Bebek doğmadan önce de duyduğu kalp ritmini tanır; bu ses onu güvende hissettirir ve kendi nefesini düzenlemesine yardım eder.',
     'Yalnız kucakta sallanın, göğse yatırmayın.',
     'Kalp sesine eşlik eden çok alçak bir mırıltı ekleyin.',
     'Birkaç dakika içinde nefesinin yavaşlayıp yavaşlamadığına bakın.',
     'Bebeğin burnu ve ağzı açıkta kalsın, yüzü yana dönük olsun.'),
    (134, 'Bebeği karşınıza oturtun ya da yatırın, aranıza küçük bir nesne koyun.', 'Nesne sürekliliği kavramını sessizce çalıştırmak.',
     'Görünmeyen şeyin var olmaya devam ettiğini anlamak, bebeğin ilk soyut düşüncesidir; bu kavram ayrılık kaygısının yumuşamasına da yardım eder.',
     'Nesnenin yarısı görünecek şekilde örtün.',
     'İki örtü kullanıp nesneyi hangisinin altına koyduğunuzu hatırlamasını isteyin.',
     'Örtüyü kaldırıp kaldırmadığına, kaldırmıyorsa nesneye bakmaya devam edip etmediğine dikkat edin.',
     'Örtü ince ve nefes alabilir olsun, bebeğin yüzüne yaklaştırmayın.'),
    (135, 'Yere iki üç yastık dizin, aralarında bir adım mesafe olsun.', 'Dengeyi ve adım kontrolünü gürültüsüz çalıştırmak.',
     'Yürümeyi yeni öğrenen çocuk zemin değiştikçe dengesini yeniden kurmayı öğrenir; bu, düşmeden yapılabilecek en sade denge çalışmasıdır.',
     'Tek yastık koyun, sadece üstüne çıkıp inmesi yeterli olsun.',
     'Elini bırakıp yanında yürüyün, kendi dengesini kurmasını bekleyin.',
     'Adım atarken gözünü yastığa mı yoksa size mi çevirdiğine bakın.',
     'Yastıklar kaymayan bir zeminde olsun, çevrede sert köşe bulunmasın.'),
    (136, 'Yere karşılıklı oturun, aranızda bir kol mesafesi olsun.', 'Büyük kas gruplarını taklit yoluyla, hiç hızlanmadan çalıştırmak.',
     'Taklit, bu yaşın en güçlü öğrenme yoludur; yavaş tempo aşırı uyarandan kaçınan çocuğun hareketi izleyip kopyalamasına zaman tanır.',
     'Yalnız kolları yukarı kaldırma hareketini yapın.',
     'Hareketleri çocuğun başlatmasını isteyin, siz taklit edin.',
     'Sizi izleyip izlemediğine, kendi başına başlatıp başlatmadığına bakın.',
     'Zorlamayın, esnetme yapmayın, hareketler çocuğun kendi sınırında kalsın.'),
    (137, 'Kucağınıza alın, sade resimli bir kitap seçin.', 'Kelime dağarcığını sakin bir ortamda büyütmek.',
     'Bu yaşta kelime patlaması başlar; ama kalabalık sayfalar ve yüksek sesli anlatım hassas çocuğu kapatır. Tek nesne, alçak ses, bol bekleme en verimli formattır.',
     'Kitabı kapatın, yalnız kapaktaki tek nesneyi konuşun.',
     'Nesneyi siz göstermeyin, "kedi nerede" diye sorup bulmasını bekleyin.',
     'Parmağıyla gösteriyor mu, sesle tekrar ediyor mu, hangisi önce geliyor?',
     'Kitap sayfaları kalın olsun, ağzına götürürse ıslanmasın.'),
    (138, 'Yerde karşılıklı oturun, aranızda bir kol mesafesi bırakın.', 'Sıra alma davranışını sessizce kurmak.',
     'Sıra almak, sosyal gelişimin ilk kuralıdır; top yuvarlamak bu kuralı kelimesiz öğretir, üstelik hiç gürültü çıkarmaz.',
     'Topu yalnız siz yuvarlayın, geri getirmesi yeterli olsun.',
     'Mesafeyi biraz açın ya da topu hangi elle iteceğini belirtin.',
     'Topu geri yuvarlamadan önce size bakıyor mu? Bakışla sıra alıyorsa sosyal beceri gelişiyor demektir.',
     'Top yumuşak ve sessiz olsun, sert plastik kullanmayın.'),
    (139, 'Sade bir kutu ve üç dört yumuşak nesne hazırlayın, yanına oturun.', 'İçinde ve dışında kavramını el becerisiyle birlikte kurmak.',
     'Nesneleri bir kaba koyup çıkarmak, çocuğun ilk sınıflandırma denemesidir; anne yanında ama karışmadığında çocuk kendi temposunu bulur.',
     'Tek nesneyle başlayın, yalnız kutuya bırakması yeterli.',
     'Nesneleri renklerine göre iki ayrı kutuya ayırmasını isteyin.',
     'Nesneleri rastgele mi atıyor, yoksa tek tek yerleştiriyor mu?',
     'Kutu kenarları keskin olmasın, nesneler yutulabilecek boyutta olmasın.'),
    (140, 'Pencere kenarına kucağınızda ya da yanınızda oturtun.', 'Doğal uyaranla sakin gözlem kurmak.',
     'Aşırı uyarandan kaçınan çocuğun duyusal sistemi, yavaş ve öngörülebilir doğa hareketleriyle (bulut, yaprak) rahatlar; bu bir dinlenme etkinliğidir.',
     'Yalnız bir dakika bakın, sonra bitirin.',
     'Gördüğü şeyi göstermesini isteyin, siz adlandırın.',
     'Kaç dakika bakabildiğine ve neye takıldığına dikkat edin.',
     'Pencere önü güvenli olsun, çocuk tek başına bırakılmasın.'),
    (141, 'Sessiz bir köşede karşılıklı oturun, kuklayı elinize takın.', 'Karşılıklı konuşmayı gürültüsüz bir çerçevede çalıştırmak.',
     'Bu yaş dilin en hızlı geliştiği dönem; kukla, çocuğun doğrudan göz teması baskısı olmadan konuşmasını sağlar, fısıltı da ortamı sakin tutar.',
     'Kukla yalnız selam verip şarkı mırıldansın, soru sormasın.',
     'Kuklayı çocuğa verin, o size soru sorsun.',
     'Kuklaya mı yoksa size mi cevap veriyor? Kuklaya cevap veriyorsa oyun tutmuş demektir.',
     'Kukla yumuşak olsun, ani hareket ettirmeyin.'),
    (142, 'Sessiz bir masada yan yana oturun, kartları ters çevirip yanınıza koyun.', 'Bilinen kelimeleri pekiştirmek ve yenilerini eklemek.',
     'Adlandırma, dilin temel taşıdır; sade zeminli tek nesneli kartlar hassas çocuğun dikkatini dağıtmaz.',
     'Bildiği iki nesneyle sınırlayın, yeni kelime eklemeyin.',
     'Nesnenin ne işe yaradığını da sormaya başlayın.',
     'Kelimeyi kendi mi söylüyor yoksa sizin söylemenizi mi bekliyor?',
     'Kart kenarları keskin olmasın.'),
    (143, 'Yan yana ya da kucakta oturun, ışıkları kısın.', 'Kendini yatıştırma becerisini öğretmek.',
     'Öz-düzenleme öğrenilen bir beceridir; sakin anda öğretilirse zor anda kullanılabilir. Aşırı uyarandan kaçınan çocuk için bu beceri özellikle kıymetlidir.',
     'Yalnız siz nefes alın, o elini karnınıza koyup hissetsin.',
     'Nefes sayısını beşe çıkarın ya da nefesi kendi başlatmasını isteyin.',
     'Karnının hareketini fark ediyor mu? Nefesi sizinle eşleşiyor mu?',
     'Zorlamayın, derin nefes ısrarı yapmayın; baş dönmesi olursa bırakın.'),
    (144, 'Masaya üç çift nesne karışık şekilde koyun, yanına oturun.', 'Eşleştirme ve benzerlik kavramını çalıştırmak.',
     'Eşleştirme, sınıflandırmanın ilk adımıdır ve matematiksel düşünmenin temelini kurar. Sessiz malzemelerle yapıldığında hassas çocuk da uzun süre odaklanabilir.',
     'İki çiftle başlayın, biri çok belirgin farklı olsun.',
     'Beş çifte çıkarın ya da gözünü kapatıp dokunarak eşleştirmesini isteyin.',
     'Eşi ararken bakışını nasıl gezdiriyor? Sistemli mi, rastgele mi?',
     'Küçük parçalı nesne kullanmayın.'),
    (145, 'Aynanın karşısına yan yana oturun ya da durun.', 'Duyguları tanımayı ve adlandırmayı başlatmak.',
     'Duyguyu adlandırabilen çocuk, onu yönetmeye de başlar. Ayna, çocuğun kendi ifadesini görmesini sağladığı için bu öğrenmeyi hızlandırır.',
     'Yalnız mutlu ve üzgün yüzle sınırlayın.',
     'Siz bir duygu yapın, o adlandırsın; sonra rol değişsin.',
     'Kendi yüzüne mi yoksa sizinkine mi bakıyor? Duyguyu adlandırabiliyor mu?',
     'Ayna sabit ve güvenli olmalı, duvara monte tercih edilir.'),
    (146, 'Karşılıklı oturun, elleriniz masada ya da dizinizde olsun.', 'Ritim algısını gürültüsüz kurmak.',
     'Ritim, dilin ve hareketin ortak temelidir. Yüksek sesli enstrümanlar hassas çocuğu kapatır; parmak ucu vuruşu aynı beceriyi sessizce çalıştırır.',
     'İki vuruşla sınırlayın (tak tak).',
     'Dört vuruşluk kalıplar yapın ya da ritmi çocuk başlatsın.',
     'Vuruş sayısını doğru tekrarlıyor mu? Yoksa yalnız hareketi mi taklit ediyor?',
     'Sert yüzeye vurdurtmayın, parmak ucu yeterli.'),
    (147, 'Yatmadan önce loş ışıkta yan yana oturun.', 'Olayları sırayla anlatma becerisini kurmak.',
     'Bu yaşta çocuk kelimeleri cümleye, cümleleri sıraya dizmeyi öğrenir. Gün anlatımı hem dili hem belleği çalıştırır, üstelik hiçbir malzeme gerektirmez.',
     'Tek bir olayı sorun ("Bugün ne yedin?").',
     'Sırayı sorun: "Önce ne oldu, sonra ne oldu?"',
     'Kaç cümle kurabiliyor? Olayları sırasıyla mı anlatıyor?',
     'Anlatmak istemezse ısrar etmeyin, siz kendi gününüzü anlatın.'),
    (148, 'Sakin bir ortamda karşılıklı oturun.', 'Neden sonuç bağı kuran cümleler üretmesini sağlamak.',
     'Varsayım kurmak soyut düşüncenin başlangıcıdır; bu yaşta çocuk "eğer" cümlelerini anlamaya başlar ve dil bu sayede düşünme aracına dönüşür.',
     'Yalnız iki seçenekli sorun: "Yağmur yağarsa şemsiye mi alırız, mont mu?"',
     'Çocuk soru sorsun, siz cevaplayın.',
     'Cevabı mantıklı mı, yoksa aklına ilk geleni mi söylüyor?',
     'Korkutucu senaryolar sormayın.'),
    (149, 'Evin sakin bir köşesini birlikte seçin.', 'Çocuğa kendi sakinleşme alanını tanımlamak.',
     'Kendi alanını kuran çocuk, o alana ihtiyaç duyduğunda kendi gider. Bu, öz-düzenlemenin en kalıcı biçimidir ve hassas çocuk için bir sığınak yaratır.',
     'Siz kurun, o yalnız yastığı yerleştirsin.',
     'Köşede ne olacağına tamamen kendisi karar versin.',
     'Kurduktan sonra kendi başına gidiyor mu? Ne zaman gidiyor?',
     'Köşe kapalı bir alan olmasın, görüş açık kalsın.'),
    (150, 'Masaya farklı boyutta üç dört nesne karışık koyun.', 'Boyut kavramını ve sıralama kuralını çalıştırmak.',
     'Sıralama, matematiksel düşünmenin çekirdeğidir: çocuk bir kuralı akılda tutup tüm nesnelere uygulamayı öğrenir.',
     'İki nesneyle başlayın, aralarındaki fark belirgin olsun.',
     'Beş nesneye çıkarın ya da büyükten küçüğe dizmesini isteyin.',
     'Kuralı tutarlı uyguluyor mu, yoksa ortada bozuluyor mu?',
     'Nesneler kırılmaz olsun.'),
    (151, 'Masada karşılıklı oturun, önünüze birkaç blok koyun.', 'Sıra beklemeyi ve kurala uymayı çalıştırmak.',
     'Sıra beklemek, okul öncesi dönemin en kritik sosyal becerisidir. Sessiz bir masa oyununda öğrenilirse kalabalık ortamda da kullanılabilir.',
     'İki turda bitirin, bekleme süresi kısa olsun.',
     'Sırayı unutma oyunu ekleyin: kim unutursa bir tur atlar.',
     'Sırasını beklerken ne yapıyor? Sabırsızlanıyor mu, izliyor mu?',
     'Kaybetme durumu yaratmayın, bu bir yarışma değil.'),
    (152, 'Masaya doğal nesneleri dizin, yanına oturun ama karışmayın.', 'Doğal dokuları sakin ve bağımsıza yakın bir kurulumda keşfettirmek.',
     'Doğal nesneler yapay oyuncaklardan daha sade uyaran taşır: parlamaz, ses çıkarmaz, beklenmedik hareket etmez. Hassas çocuk için ideal keşif malzemesidir.',
     'İki nesneyle başlayın, siz de birlikte dokunun.',
     'Nesneleri dokusuna göre gruplamasını isteyin.',
     'Hangi dokuda daha uzun kalıyor? Hangisinden kaçınıyor?',
     'Nesneleri önceden yıkayın, küçük ve yutulabilir parça bırakmayın.'),
    (153, 'Masada karşılıklı oturun, duygu kartlarını ters çevirin.', 'Duyguları tanıyıp kendi deneyimiyle eşleştirmesini sağlamak.',
     'Okul öncesi dönemin dönem görevi sosyal-duygusal gelişimdir. Duyguyu adlandırıp örnekleyebilen çocuk, hem kendini hem başkasını daha iyi anlar.',
     'İki kartla sınırlayın (mutlu, üzgün), örnek vermesi zorunlu olmasın.',
     'Kartı çekmeden siz bir olay anlatın, o duyguyu tahmin etsin.',
     'Kendi deneyiminden örnek verebiliyor mu, yoksa genel mi konuşuyor?',
     'Üzücü anıya takılırsa konuyu değiştirin, ısrar etmeyin.'),
    (154, 'Yatmadan önce yan yana oturun, ışıkları kısın.', 'Olumlu duyguları fark etme ve ifade etme alışkanlığı kurmak.',
     'Minnet ifadesi, duygu düzenlemesinin en basit ve en güçlü araçlarından biridir; günü olumlu bir notla kapatmak uykuya geçişi de kolaylaştırır.',
     'Tek şey söylemesi yeterli olsun, siz iki tane söyleyin.',
     'Neden teşekkür ettiğini de açıklamasını isteyin.',
     'Kendi hayatından mı örnek veriyor, yoksa sizinkini mi tekrarlıyor?',
     'Zorunlu tutmayın; söylemek istemezse siz söyleyin, dinlemesi yeterli.'),
    (155, 'Sakin bir ortamda karşılıklı ya da yan yana oturun.', 'Anlatı kurma ve sırayla katkı verme becerisini birleştirmek.',
     'Kendi hikâyesini kuran çocuk dili düşünme aracı olarak kullanmaya başlar; sıra alma kuralı da sosyal beceriyi aynı anda çalıştırır.',
     'Siz üç cümle söyleyin, o yalnız sonunu tamamlasın.',
     'Hikâyeyi tamamen çocuk kursun, siz yalnız dinleyin.',
     'Hikâyeye kendi öğelerini ekliyor mu, yoksa sizinkini mi tekrarlıyor?',
     'Korkutucu yöne giderse yumuşatın.'),
    (156, 'Masaya kâğıt ve birkaç kalem koyun, yanına oturun.', 'Duyguyu sözsüz ifade etmenin bir yolunu kazandırmak.',
     'Bazı çocuklar duygusunu anlatamaz ama çizebilir. Hava durumu benzetmesi soyut duyguyu somutlaştırır ve anne için de okunabilir bir işaret olur.',
     'Üç seçenekten birini işaretlemesi yeterli olsun, çizmesin.',
     'Havanın gün içinde nasıl değiştiğini de çizmesini isteyin.',
     'Hangi simgeyi seçiyor? Seçimi gün boyunca gözlemlediklerinizle uyuşuyor mu?',
     'Çizimi yorumlamayın, "neden böyle çizdin" diye sorgulamayın.'),
    (157, 'Bir nesneyi kutuya koyup kapatın, çocuğa göstermeyin.', 'İpuçlarından sonuç çıkarma becerisini çalıştırmak.',
     'Tahmin etmek, eldeki bilgiyle akıl yürütmektir. Görsel uyaran olmadan yalnız dokunmayla yapılması hem odaklanmayı artırır hem duyusal yükü düşük tutar.',
     'Nesneyi önce gösterip sonra kutuya koyun, hatırlaması yeterli olsun.',
     'Üç nesne koyup hepsini sırayla tahmin etmesini isteyin.',
     'Tahmin ederken hangi özellikleri söylüyor (sert, yumuşak, uzun)?',
     'Kutuya keskin ya da kırılabilir nesne koymayın.'),
    (158, 'Sakin bir ortamda karşılıklı oturun.', 'Bakış açısı alma ve sosyal problem çözme becerisini geliştirmek.',
     'Okula hazırlığın özü, başkasının ne hissettiğini anlayıp ona göre davranabilmektir. Bu yaşta çocuk artık kendi dışındaki bakış açısını kurabilir.',
     'İki seçenek sunun, birini seçmesi yeterli olsun.',
     'Durumu o kursun, siz cevaplayın.',
     'Kendi isteğinden mi konuşuyor, yoksa karşıdakini düşünebiliyor mu?',
     'Gerçek bir çatışmayı örnek vermeyin, kurgu kalsın.'),
    (159, 'Masada yan yana oturun, kâğıt ve kalem alın.', 'Planlama ve söz verme becerisini kurmak.',
     'Kendi gününü planlayan çocuk sorumluluk duygusu geliştirir; okul düzenine geçişte en çok işe yarayan beceri budur.',
     'İki iş konuşun, sıralamayı siz yapın.',
     'Haftalık plan yapın, her akşam birlikte kontrol edin.',
     'Kendi önerisini getiriyor mu, yoksa sizinkini mi onaylıyor?',
     'Yapılamayan plan için suçlayıcı olmayın.'),
    (160, 'Sessiz bir odada karşılıklı oturun, saat ya da kum saati koyun.', 'Bekleme becerisini ve iç dikkati çalıştırmak.',
     'Bekleyebilen çocuk dürtüsünü yönetmeyi öğrenir. Bu beceri, okul başarısının en güçlü yordayıcılarından biridir ve sessiz alıştırmayla gelişir.',
     'Süreyi otuz saniyeye indirin.',
     'İki dakikaya çıkarın ya da gözlerini kapatmasını isteyin.',
     'Süre boyunca ne yapıyor? Kıpırdanıyor mu, dinliyor mu?',
     'Başaramazsa sorun etmeyin, süre kısaltılır.'),
    (161, 'Kâğıdı üçe katlayın, kalemleri koyun, yanına oturun ama karışmayın.', 'Kendi anlatısını baştan sona kurmasını sağlamak.',
     'Bu yaşta çocuk artık kendi kurgusunu üretebilir. Kitap formatı, hikâyenin başı ortası sonu olduğunu somutlaştırır.',
     'Tek sayfa çizsin, siz sonunu sorun.',
     'Sayfalara yazı da eklemesini isteyin (harf denemeleri olsa da olur).',
     'Hikâyede başlangıç, ortada bir olay ve son var mı?',
     'Çizimini yorumlamayın, "bu ne" diye sorgulamayın.'),
    (162, 'Kâğıda basit bir labirent çizin, kalemi verin.', 'Uzamsal planlama ve deneme yanılma becerisini çalıştırmak.',
     'Labirent çözmek, önden planlamayı gerektirir: çocuk yolu gözüyle takip edip kararını önceden verir. Sessiz ve tek başına yapılabilen ideal bir bilişsel çalışmadır.',
     'Çok basit, tek dönüşlü bir labirent çizin.',
     'Kendi labirentini çizip size çözdürmesini isteyin.',
     'Kalemi hemen mi bastırıyor, yoksa önce gözüyle mi izliyor?',
     'Kalem ucu sivri olmasın.')
ON CONFLICT (activity_id) DO UPDATE SET
    intro = EXCLUDED.intro,
    purpose = EXCLUDED.purpose,
    why_it_matters = EXCLUDED.why_it_matters,
    easier_variation = EXCLUDED.easier_variation,
    harder_variation = EXCLUDED.harder_variation,
    observation_tip = EXCLUDED.observation_tip,
    safety_notes = EXCLUDED.safety_notes;

DELETE FROM activity_steps WHERE activity_id IN (129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162);
INSERT INTO activity_steps (activity_id, step_no, text) VALUES
    (129, 1, 'Bebeği sırtüstü yatırın ve göz teması kurun.'),
    (129, 2, 'Bir elinizle kalçasını, diğeriyle omzunu çok hafifçe destekleyin.'),
    (129, 3, 'Beş saniyede bir tam dönüş olacak yavaşlıkta yana çevirin.'),
    (129, 4, 'Yan yatışta üç saniye bekleyin.'),
    (129, 5, 'Aynı yavaşlıkta sırtüstü getirin, iki kez tekrarlayın.'),
    (130, 1, 'Nesneyi bebeğin görebileceği ama ulaşamayacağı yere koyun.'),
    (130, 2, 'Adını söyleyip nesneyi hafifçe hareket ettirin.'),
    (130, 3, 'Uzandığında nesneye dokunmasına izin verin.'),
    (130, 4, 'Nesneyi bir karış yana alın, gövdesini çevirmesini bekleyin.'),
    (130, 5, 'Aldığında birlikte sevinin, oyunu bitirin.'),
    (131, 1, 'Bebeği kucağınıza alın, göz teması kurun.'),
    (131, 2, 'Adını üç kez, aralarında bekleyerek fısıldayın.'),
    (131, 3, 'Tepki verirse (bakış, ses, hareket) bekleyip ona sıra verin.'),
    (131, 4, 'Yakınındaki bir nesnenin adını fısıldayın.'),
    (131, 5, 'Sessizlikle bitirin.'),
    (132, 1, 'Odayı loşlaştırın.'),
    (132, 2, 'Nesneyi bebeğin göz hizasında yarım karış uzakta tutun.'),
    (132, 3, 'Baktığından emin olun.'),
    (132, 4, 'Çok yavaşça sağa, sonra sola götürün.'),
    (132, 5, 'Gözü ayrılırsa durun, tekrar dikkatini çekin.'),
    (133, 1, 'Rahat bir koltukta oturun.'),
    (133, 2, 'Bebeği göğsünüze, kulağı kalbinize gelecek şekilde yatırın.'),
    (133, 3, 'Elinizi sırtına koyun, hareket etmeyin.'),
    (133, 4, 'Üç dakika sessiz kalın.'),
    (133, 5, 'Bebek gevşediğinde yatağına alın.'),
    (134, 1, 'Nesneyi bebeğe gösterin, dokunmasına izin verin.'),
    (134, 2, 'Gözü üstündeyken ince örtüyle yavaşça örtün.'),
    (134, 3, 'Bekleyin, acele etmeyin.'),
    (134, 4, 'Bulamazsa örtünün ucunu hafifçe kaldırın.'),
    (134, 5, 'Bulduğunda sessizce gülümseyerek onaylayın.'),
    (135, 1, 'Yastıkları dizin, çocuğa gösterin.'),
    (135, 2, 'İki elinden tutun.'),
    (135, 3, 'İlk yastığa çıkmasını bekleyin, acele ettirmeyin.'),
    (135, 4, 'Yastıktan yastığa geçin.'),
    (135, 5, 'Sonda birlikte oturup dinlenin.'),
    (136, 1, 'Karşılıklı oturun.'),
    (136, 2, 'Kollarınızı yavaşça yukarı kaldırın, bekleyin.'),
    (136, 3, 'Çocuk taklit edene kadar tutun.'),
    (136, 4, 'Öne doğru uzanın, aynı şekilde bekleyin.'),
    (136, 5, 'Üç hareketle bitirin.'),
    (137, 1, 'Kucağınıza alın, kitabı birlikte tutun.'),
    (137, 2, 'İlk sayfayı açın, tek nesneyi gösterip adını söyleyin.'),
    (137, 3, 'Beş saniye bekleyin.'),
    (137, 4, 'Tepki verirse tekrarlayın.'),
    (137, 5, 'Üç dört sayfada bitirin.'),
    (138, 1, 'Karşılıklı oturun.'),
    (138, 2, 'Topu yavaşça ona doğru yuvarlayın.'),
    (138, 3, 'Alması ve size bakması için bekleyin.'),
    (138, 4, 'Geri yuvarlamasını isteyin, acele ettirmeyin.'),
    (138, 5, 'Beş tur sonra bitirin.'),
    (139, 1, 'Kutuyu ve nesneleri önüne koyun.'),
    (139, 2, 'Bir nesneyi kutuya koyup gösterin.'),
    (139, 3, 'Geri çekilin, kendi denemesini bekleyin.'),
    (139, 4, 'Tıkanırsa tek hamle gösterin.'),
    (139, 5, 'Kutu dolunca birlikte boşaltın.'),
    (140, 1, 'Pencere kenarına oturun.'),
    (140, 2, 'Hiçbir şey söylemeden birlikte dışarı bakın.'),
    (140, 3, 'Bir şeye takılırsa siz de oraya bakın.'),
    (140, 4, 'İsterse tek kelimeyle adlandırın.'),
    (140, 5, 'İlgisi dağılınca bitirin.'),
    (141, 1, 'Kuklayı elinize takın, yavaşça ortaya çıkarın.'),
    (141, 2, 'Kukla fısıltıyla selam versin.'),
    (141, 3, 'Çocuğun cevabını bekleyin, acele ettirmeyin.'),
    (141, 4, 'Kukla tek bir soru sorsun ("Bugün ne yaptın?").'),
    (141, 5, 'Cevap gelince kukla teşekkür edip vedalaşsın.'),
    (142, 1, 'İlk kartı çevirin, göstermeden önce bekleyin.'),
    (142, 2, 'Kartı gösterin, hiçbir şey söylemeyin.'),
    (142, 3, 'Çocuk adlandırmazsa siz söyleyin, tekrarlamasını bekleyin.'),
    (142, 4, 'Doğru söylerse onaylayın.'),
    (142, 5, 'Dört kartta bitirin.'),
    (143, 1, 'Ellerinizi karnınıza koyun, ona da koydurun.'),
    (143, 2, '"Balonu şişiriyoruz" deyip yavaşça nefes alın.'),
    (143, 3, '"Şimdi söndürüyoruz" deyip yavaşça verin.'),
    (143, 4, 'Üç kez tekrarlayın.'),
    (143, 5, 'Sessizce oturup bitirin.'),
    (144, 1, 'Nesneleri karışık dizin.'),
    (144, 2, 'Bir nesneyi alıp eşini aramasını isteyin.'),
    (144, 3, 'Geri çekilin, aramasını bekleyin.'),
    (144, 4, 'Bulunca yan yana koydurun.'),
    (144, 5, 'Üç çift bitince toplayın.'),
    (145, 1, 'Aynanın karşısına geçin.'),
    (145, 2, 'Mutlu bir yüz yapıp "mutlu" deyin.'),
    (145, 3, 'Taklit etmesini bekleyin.'),
    (145, 4, 'Üzgün yüzle tekrarlayın.'),
    (145, 5, 'Üç duyguyla bitirin.'),
    (146, 1, 'Masaya parmak ucuyla iki kez hafifçe vurun.'),
    (146, 2, 'Bekleyin, tekrarlamasını isteyin.'),
    (146, 3, 'Doğru yaparsa onaylayın.'),
    (146, 4, 'Üç vuruşluk kalıba geçin.'),
    (146, 5, 'Beş turda bitirin.'),
    (147, 1, 'Loş ışıkta yan yana oturun.'),
    (147, 2, '"Bugün ne yaptık?" diye sorun.'),
    (147, 3, 'Cevabı bekleyin, sözünü kesmeyin.'),
    (147, 4, '"Sonra ne oldu?" diye devam ettirin.'),
    (147, 5, 'Üç cümle olunca teşekkür edip bitirin.'),
    (148, 1, 'Karşılıklı oturun.'),
    (148, 2, '"Yağmur yağarsa ne yaparız?" diye sorun.'),
    (148, 3, 'Düşünmesi için bekleyin.'),
    (148, 4, 'Cevabını genişletin, düzeltmeyin.'),
    (148, 5, 'İki üç soruda bitirin.'),
    (149, 1, 'Birlikte sakin bir köşe seçin.'),
    (149, 2, 'Yastık ve battaniyeyi birlikte yerleştirin.'),
    (149, 3, '"Burası senin sakin köşen" deyin.'),
    (149, 4, 'Birlikte oturup bir dakika sessiz kalın.'),
    (149, 5, 'İstediğinde gelebileceğini söyleyin.'),
    (150, 1, 'Nesneleri karışık dizin.'),
    (150, 2, '"En küçüğü hangisi?" diye sorun.'),
    (150, 3, 'Sıraya dizmesini isteyin, karışmayın.'),
    (150, 4, 'Takılırsa yalnız bir nesneyi doğru yere koyun.'),
    (150, 5, 'Bitince birlikte bakın.'),
    (151, 1, 'Blokları ortaya koyun.'),
    (151, 2, '"Önce ben" deyip bir blok koyun.'),
    (151, 3, '"Şimdi sen" deyin, bekleyin.'),
    (151, 4, 'Her turda sırayı sesli söyleyin.'),
    (151, 5, 'Altı blok bitince kule tamam, birlikte bakın.'),
    (152, 1, 'Nesneleri masaya dizin.'),
    (152, 2, '"İstediğin gibi bakabilirsin" deyip geri çekilin.'),
    (152, 3, 'Karışmadan izleyin.'),
    (152, 4, 'Bir şey sorarsa kısaca cevaplayın.'),
    (152, 5, 'İlgisi bitince birlikte toplayın.'),
    (153, 1, 'Kartları ters çevirip dizin.'),
    (153, 2, 'Bir kart çekip duyguyu adlandırmasını isteyin.'),
    (153, 3, '"Sen ne zaman böyle hissettin?" diye sorun.'),
    (153, 4, 'Anlatmasını bekleyin, yorum yapmayın.'),
    (153, 5, 'Üç kartta bitirin.'),
    (154, 1, 'Işıkları kısıp yan yana oturun.'),
    (154, 2, 'Siz bir teşekkür söyleyin.'),
    (154, 3, 'Sıra ona geçsin, bekleyin.'),
    (154, 4, 'Üç tur dönün.'),
    (154, 5, 'Sessizce bitirin.'),
    (155, 1, '"Bir varmış bir yokmuş, küçük bir kedi varmış" diye başlayın.'),
    (155, 2, 'Sıra ona geçsin, bekleyin.'),
    (155, 3, 'Kısa bir cümleyle devam edin.'),
    (155, 4, 'Beş turda hikâyeyi bitirin.'),
    (155, 5, 'Birlikte hikâyeye isim koyun.'),
    (156, 1, 'Kâğıdı ve kalemleri koyun.'),
    (156, 2, '"Bugün havan nasıldı?" diye sorun.'),
    (156, 3, 'Güneş, bulut, yağmur örneklerini gösterin.'),
    (156, 4, 'Çizmesini bekleyin, karışmayın.'),
    (156, 5, 'Çizimi birlikte asın ya da saklayın.'),
    (157, 1, 'Nesneyi kutuya koyun, kapağı kapatın.'),
    (157, 2, 'Elini sokup dokunmasını isteyin.'),
    (157, 3, '"Nasıl bir şey?" diye sorun, tarif etmesini bekleyin.'),
    (157, 4, 'Tahminini söylesin.'),
    (157, 5, 'Kutuyu açıp birlikte bakın.'),
    (158, 1, 'Kısa bir durum anlatın ("Arkadaşın oyuncağını kırdı, üzgün").'),
    (158, 2, '"Sen olsan ne yapardın?" diye sorun.'),
    (158, 3, 'Düşünmesi için bekleyin.'),
    (158, 4, 'Cevabını genişletin, düzeltmeyin.'),
    (158, 5, 'İki durumda bitirin.'),
    (159, 1, '"Yarın ne yapmak istersin?" diye sorun.'),
    (159, 2, 'İki üç öneriyi yazın ya da çizin.'),
    (159, 3, 'Hangisi önce olsun diye sorun.'),
    (159, 4, 'Sıraya koyun.'),
    (159, 5, 'Kâğıdı görünür bir yere asın.'),
    (160, 1, 'Kum saatini çevirin.'),
    (160, 2, '"Bir dakika hiç konuşmadan dinleyelim" deyin.'),
    (160, 3, 'Birlikte sessiz oturun.'),
    (160, 4, 'Süre bitince ne duyduğunu sorun.'),
    (160, 5, 'Siz de duyduklarınızı söyleyin.'),
    (161, 1, 'Kâğıdı üçe katlayıp kitap yapın.'),
    (161, 2, '"Kendi hikâyeni çiz" deyin.'),
    (161, 3, 'Geri çekilin, karışmayın.'),
    (161, 4, 'Bitince anlatmasını isteyin.'),
    (161, 5, 'Kitabı birlikte saklayın.'),
    (162, 1, 'Basit bir labirent çizin.'),
    (162, 2, 'Başlangıç ve bitişi gösterin.'),
    (162, 3, 'Çözmesini bekleyin, yol göstermeyin.'),
    (162, 4, 'Bitince birlikte bakın.'),
    (162, 5, 'İsterse kendi labirentini çizsin.');

DELETE FROM activity_materials WHERE activity_id IN (129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162);
INSERT INTO activity_materials (activity_id, name, note, is_optional) VALUES
    (129, 'Yumuşak minder ya da oyun matı', 'Zemin sert olmasın', FALSE),
    (129, 'İnce battaniye', 'Üstünü örtmek için', TRUE),
    (130, 'Yumuşak oyuncak ya da kumaş top', 'Sessiz olanı tercih edin', FALSE),
    (131, 'Sessiz bir oda', 'Televizyon ve müzik kapalı', FALSE),
    (132, 'Sade renkli tek nesne', 'Parlamayan, ses çıkarmayan', FALSE),
    (133, 'Rahat koltuk', 'Sırtınız desteklensin', FALSE),
    (134, 'Küçük yumuşak nesne', 'Ses çıkarmayan', FALSE),
    (134, 'İnce kumaş örtü', 'Tülbent ya da ince muslin', FALSE),
    (135, 'İki üç yastık', 'Sert olmayan', FALSE),
    (136, 'Yumuşak zemin', 'Halı ya da mat', TRUE),
    (137, 'Kalın sayfalı resimli kitap', 'Sayfa başına tek nesne olanı tercih edin', FALSE),
    (138, 'Yumuşak top', 'Kumaş ya da sünger', FALSE),
    (139, 'Sade kutu ya da sepet', 'Kapaksız', FALSE),
    (139, 'Üç dört yumuşak nesne', 'Yutulmayacak boyutta', FALSE),
    (140, 'Pencere', 'Güvenli, açılmayan', FALSE),
    (141, 'Yumuşak el kuklası', 'Ses çıkarmayan', FALSE),
    (142, 'Sade resimli kartlar', 'Tek nesne, düz zemin', FALSE),
    (143, 'Sessiz oda', 'Loş ışık tercih edilir', TRUE),
    (144, 'Üç çift aynı nesne', 'Çorap, kaşık, blok gibi', FALSE),
    (145, 'Ayna', 'Sabit ve güvenli', FALSE),
    (146, 'Masa ya da diz', 'Sert olmayan yüzey tercih edin', TRUE),
    (147, 'Sessiz oda', 'Yatmadan önce ideal', FALSE),
    (148, 'Sessiz oda', 'Malzeme gerekmez', TRUE),
    (149, 'İki yastık', 'Yumuşak', FALSE),
    (149, 'Battaniye', 'İnce', TRUE),
    (150, 'Farklı boyutta üç dört nesne', 'Kap, blok ya da kaşık', FALSE),
    (151, 'Altı blok', 'Sessiz malzeme', FALSE),
    (152, 'Üç dört doğal nesne', 'Taş, yaprak, kozalak; yıkanmış', FALSE),
    (152, 'Tepsi', 'Nesneleri toplamak için', TRUE),
    (153, 'Duygu yüzü kartları', 'Sade çizimli, dört duygu yeterli', FALSE),
    (154, 'Sessiz oda', 'Yatmadan önce ideal', TRUE),
    (155, 'Sessiz oda', 'Malzeme gerekmez', TRUE),
    (156, 'Kâğıt', 'A5 yeterli', FALSE),
    (156, 'Üç dört kalem', 'Sade renkler', FALSE),
    (157, 'Kapaklı kutu', 'El sığacak açıklığı olan', FALSE),
    (157, 'Bir nesne', 'Tanıdık, güvenli', FALSE),
    (158, 'Sessiz oda', 'Malzeme gerekmez', TRUE),
    (159, 'Kâğıt', 'A5 yeterli', FALSE),
    (159, 'Kalem', 'Tek renk yeterli', FALSE),
    (160, 'Kum saati ya da telefon zamanlayıcısı', 'Sesi kapalı olsun', FALSE),
    (161, 'Kâğıt', 'A4, üçe katlanacak', FALSE),
    (161, 'Kalemler', 'Sade renkler', FALSE),
    (162, 'Kâğıt', 'A5 yeterli', FALSE),
    (162, 'Kalem', 'Uçu küt', FALSE);

DELETE FROM activity_outcomes WHERE activity_id IN (129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162);
INSERT INTO activity_outcomes (activity_id, outcome) VALUES
    (129, 'Gövde rotasyonunu destekler'),
    (129, 'Boyun kontrolünü güçlendirir'),
    (129, 'Dokunsal güven duygusunu besler'),
    (130, 'Amaçlı uzanmayı destekler'),
    (130, 'Gövde çevirmeyi çalıştırır'),
    (130, 'El göz koordinasyonunu başlatır'),
    (131, 'Sesin yönünü bulmayı destekler'),
    (131, 'Dil girdisini artırır'),
    (131, 'Karşılıklı sıra almanın temelini atar'),
    (132, 'Görsel takibi geliştirir'),
    (132, 'Odaklanma süresini uzatır'),
    (132, 'Sakin uyanıklık halini destekler'),
    (133, 'Sakinleşme becerisini destekler'),
    (133, 'Bağlanmayı güçlendirir'),
    (133, 'Nefes ritmini düzenler'),
    (134, 'Nesne sürekliliğini destekler'),
    (134, 'Problem çözmeyi başlatır'),
    (134, 'Bekleme ve arama davranışını çalıştırır'),
    (135, 'Dengeyi güçlendirir'),
    (135, 'Adım kontrolünü geliştirir'),
    (135, 'Zemin değişimine uyumu destekler'),
    (136, 'Taklit becerisini geliştirir'),
    (136, 'Büyük kasları çalıştırır'),
    (136, 'Beden farkındalığını artırır'),
    (137, 'Kelime dağarcığını genişletir'),
    (137, 'Ortak dikkat kurar'),
    (137, 'Kitapla ilişkiyi başlatır'),
    (138, 'Sıra almayı öğretir'),
    (138, 'Karşılıklı etkileşimi güçlendirir'),
    (138, 'El göz koordinasyonunu destekler'),
    (139, 'Sınıflandırmanın temelini atar'),
    (139, 'İnce motor kontrolü geliştirir'),
    (139, 'Sıralı adım takibini çalıştırır'),
    (140, 'Sakin gözlem alışkanlığı kazandırır'),
    (140, 'Doğa farkındalığını artırır'),
    (140, 'Dikkat süresini uzatır'),
    (141, 'Karşılıklı konuşmayı geliştirir'),
    (141, 'Kelime kullanımını artırır'),
    (141, 'Sıra almayı pekiştirir'),
    (142, 'Kelime dağarcığını genişletir'),
    (142, 'Görsel tanımayı geliştirir'),
    (142, 'Adlandırma güvenini artırır'),
    (143, 'Kendini yatıştırmayı öğretir'),
    (143, 'Nefes farkındalığı kazandırır'),
    (143, 'Sakinleşme rutini kurar'),
    (144, 'Eşleştirme becerisini geliştirir'),
    (144, 'Benzerlik kavramını kurar'),
    (144, 'Odaklanma süresini uzatır'),
    (145, 'Duygu tanımayı geliştirir'),
    (145, 'Yüz ifadesi taklidini çalıştırır'),
    (145, 'Duygu kelimelerini öğretir'),
    (146, 'Ritim algısını geliştirir'),
    (146, 'İşitsel belleği çalıştırır'),
    (146, 'Taklit becerisini güçlendirir'),
    (147, 'Anlatı kurmayı geliştirir'),
    (147, 'Olay sıralamasını çalıştırır'),
    (147, 'Kelime dağarcığını genişletir'),
    (148, 'Varsayımsal düşünmeyi başlatır'),
    (148, 'Neden sonuç bağı kurar'),
    (148, 'Cümle kurma becerisini geliştirir'),
    (149, 'Kendi alanını tanımlamayı öğretir'),
    (149, 'Sakinleşme stratejisi kazandırır'),
    (149, 'Öz-yönetimi destekler'),
    (150, 'Sıralama kuralını öğretir'),
    (150, 'Boyut kavramını kurar'),
    (150, 'Planlı düşünmeyi çalıştırır'),
    (151, 'Sıra beklemeyi öğretir'),
    (151, 'Sabrı geliştirir'),
    (151, 'Kurala uymayı çalıştırır'),
    (152, 'Doku ayırt etmeyi geliştirir'),
    (152, 'Bağımsız keşfi destekler'),
    (152, 'Doğa farkındalığını artırır'),
    (153, 'Duygu kelimelerini geliştirir'),
    (153, 'Kendi duygusunu tanımayı öğretir'),
    (153, 'Empatinin temelini atar'),
    (154, 'Olumlu duyguyu fark etmeyi öğretir'),
    (154, 'İfade becerisini geliştirir'),
    (154, 'Gün kapanış rutini kurar'),
    (155, 'Yaratıcı anlatıyı geliştirir'),
    (155, 'Sıra almayı pekiştirir'),
    (155, 'Cümle kurma becerisini güçlendirir'),
    (156, 'Duyguyu sözsüz ifade etmeyi öğretir'),
    (156, 'Kendi halini fark etmesini sağlar'),
    (156, 'Günlük duygu takibi kurar'),
    (157, 'Akıl yürütmeyi geliştirir'),
    (157, 'Dokunsal ayırt etmeyi çalıştırır'),
    (157, 'Tarif etme dilini geliştirir'),
    (158, 'Bakış açısı almayı geliştirir'),
    (158, 'Sosyal problem çözmeyi öğretir'),
    (158, 'Empatiyi güçlendirir'),
    (159, 'Planlama becerisini geliştirir'),
    (159, 'Sorumluluk duygusu kazandırır'),
    (159, 'Zaman kavramını güçlendirir'),
    (160, 'Bekleme becerisini geliştirir'),
    (160, 'İşitsel dikkati artırır'),
    (160, 'Dürtü kontrolünü güçlendirir'),
    (161, 'Anlatı kurgusunu geliştirir'),
    (161, 'Yaratıcı üretimi destekler'),
    (161, 'Bağımsız çalışmayı çalıştırır'),
    (162, 'Uzamsal planlamayı geliştirir'),
    (162, 'Deneme yanılma stratejisi kurar'),
    (162, 'Odaklanma süresini uzatır');

SELECT setval(pg_get_serial_sequence('activities','id'), (SELECT COALESCE(MAX(id),1) FROM activities), true);

COMMIT;